project_id = "ucjjapicfrhzlrpvgrlh"

[functions.smart-ops]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.escrow-auto-release]
verify_jwt = false

[functions.confirm-receipt]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.insights-reco]
verify_jwt = false

[functions.smart-start]
verify_jwt = false
